name: "Terraform and Deploy"

on:
  push:
    branches:
      - main

jobs:
  infrastructure_and_deploy:
    name: "Infrastructure and Deploy"
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="heroku_api_key=$HEROKU_API_KEY" \
            -var="heroku_email=$HEROKU_EMAIL" \
            -var="cloudinary_api_key=$CLOUDINARY_API_KEY" \
            -var="cloudinary_api_secret=$CLOUDINARY_API_SECRET" \
            -var="cloudinary_cloud_name=$CLOUDINARY_CLOUD_NAME"

      - name: Deploy to Heroku via Git
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: "picture-viewer-iac"
        run: |
          git remote add heroku https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git
          git push heroku HEAD:refs/heads/main -f
